sudo: false
language: python
cache: pip
python:
  - "3.6"
addons:
  apt:
    packages:
    - lftp
deploy:
  skip_cleanup: true # don't remove stuff we've built
  provider: script
  script: curl https://raw.githubusercontent.com/OpenDataServices/opendataservices-deploy/master/open-contracting-standard-deploy.sh | bash -
  on:
    all_branches: true
before_install:
  - rvm default
install:
  - pip install -r requirements.txt
  - gem install bundler
  - bundle install --path vendor/bundle --binstubs
script:
  - flake8 --max-line-length 119
  - bin/mdl --style mdl.rb *.md standard
  - py.test
  - ./build_docs.sh
